name: inception

networks:
  intra:
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/wordpress

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  admin_user_password:
    file: ../secrets/admin_user_password.txt
  user_password:
    file: ../secrets/user_password.txt

services:
  mariadb:
    build: { context: ./requirements/mariadb }
    image:  mariadb
    container_name: mariadb
    env_file: .env
    environment:
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
    secrets:  [db_root_password, db_password, admin_user_password, user_password]
    volumes:
      - mariadb:/var/lib/mysql
    networks: [intra]
    restart:  on-failure
  
  wordpress:
    build: { context: ./requirements/wordpress }
    image: wordpress
    container_name: wordpress
    env_file: .env
    environment:
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USER_USERNAME: ${WP_ADMIN_USER_USERNAME}
      WP_ADMIN_MAIL: ${WP_ADMIN_MAIL}
      WP_USER_USERNAME: ${WP_USER_USERNAME}
      WP_USER_MAIL: ${WP_USER_MAIL}
      WP_USER_DISPLAY_NAME: ${WP_USER_DISPLAY_NAME}
    secrets: [db_password, admin_user_password, user_password]
    depends_on: [mariadb]
    volumes:
      - wordpress:/var/www/wordpress
    networks: [intra]
    restart: on-failure

  nginx:
    build: { context: ./requirements/nginx }
    image: nginx
    container_name: nginx
    env_file: .env
    ports:
      - "443:443"
    depends_on: [wordpress]
    volumes:
      - wordpress:/var/www/wordpress
    networks: [intra]
    restart: on-failure